(ns qlkit-material-ui.core
  (:require [cljsjs.material-ui]
            [cljs-react-material-ui.core :as ui]
            [cljs-react-material-ui.icons :as ic]
            [qlkit.core :as ql]
            [react :refer [createElement]]))

(declare material-ui material-ui-components material-ui-icons)

(defn enable-material-ui! []
  "Configure Qlkit for Material-UI React components.  Call this before calling `qlkit.qlkit/mount."
  (doall (for [[k v] (merge material-ui-components material-ui-icons)]
           (ql/register-component k v)))
  (reset! ql/make-root-component
          (fn make-root-component [children]
            (createElement (material-ui :MuiThemeProvider)
                           #js {:muiTheme (js/MaterialUIStyles.getMuiTheme js/MaterialUIStyles.lightBaseTheme)}
                           children))))

(defn- material-ui [key]
  (or (aget js/MaterialUI (name key))
      (throw (str "Unknown material-ui component " (name key)))))

(def ^:private material-ui-components
  (merge
   ;; alternate names
   {:button                 (material-ui :RaisedButton)
    :input                  (material-ui :TextField)
    :li                     (material-ui :ListItem)
    :ol                     (material-ui :List)
    :spinner                (material-ui :CircularProgress)
    :tbody                  (material-ui :TableBody)
    :td                     (material-ui :TableRowColumn)
    :th                     (material-ui :TableHeaderColumn)
    :thead                  (material-ui :TableHeader)
    :tr                     (material-ui :TableRow)
    :transient              (material-ui :Snackbar)}
   ;; standard Material-UI names
   {:app-bar                (material-ui :AppBar)                          
    :auto-complete          (material-ui :AutoComplete)                    
    :avatar                 (material-ui :Avatar)                          
    :badge                  (material-ui :Badge)                           
    :bottom-navigation      (material-ui :BottomNavigation)                
    :bottom-navigation-item (material-ui :BottomNavigationItem)            
    :card                   (material-ui :Card)                            
    :card-actions           (material-ui :CardActions)                     
    :card-header            (material-ui :CardHeader)                      
    :card-media             (material-ui :CardMedia)                       
    :card-text              (material-ui :CardText)                        
    :card-title             (material-ui :CardTitle)                       
    :checkbox               (material-ui :Checkbox)                        
    :chip                   (material-ui :Chip)                            
    :circular-progress      (material-ui :CircularProgress)                
    :date-picker            (material-ui :DatePicker)                      
    :dialog                 (material-ui :Dialog)                          
    :divider                (material-ui :Divider)                         
    :drawer                 (material-ui :Drawer)                          
    :drop-down-menu         (material-ui :DropDownMenu)                    
    :flat-button            (material-ui :FlatButton)                      
    :floating-action-button (material-ui :FloatingActionButton)            
    :font-icon              (material-ui :FontIcon)                        
    :grid-list              (material-ui :GridList)                        
    :grid-tile              (material-ui :GridTile)                        
    :icon-button            (material-ui :IconButton)                      
    :icon-menu              (material-ui :IconMenu)                        
    :linear-progress        (material-ui :LinearProgress)                  
    :list                   (material-ui :List)                            
    :list-item              (material-ui :ListItem)                        
    :menu                   (material-ui :Menu)                            
    :menu-item              (material-ui :MenuItem)                        
    :mui-theme-provider     (material-ui :MuiThemeProvider)                
    :paper                  (material-ui :Paper)                           
    :popover                (material-ui :Popover)                         
    :radio-button           (material-ui :RadioButton)                     
    :radio-button-group     (material-ui :RadioButtonGroup)                
    :raised-button          (material-ui :RaisedButton)                    
    :refresh-indicator      (material-ui :RefreshIndicator)                
    :select-field           (material-ui :SelectField)                     
    :slider                 (material-ui :Slider)                          
    :snackbar               (material-ui :Snackbar)                        
    :step                   (material-ui :Step)                            
    :step-button            (material-ui :StepButton)                      
    :step-content           (material-ui :StepContent)                     
    :step-label             (material-ui :StepLabel)                       
    :stepper                (material-ui :Stepper)                         
    :subheader              (material-ui :Subheader)                       
    :svg-icon               (material-ui :SvgIcon)                         
    :tab                    (material-ui :Tab)                             
    :table                  (material-ui :Table)                           
    :table-body             (material-ui :TableBody)                       
    :table-footer           (material-ui :TableFooter)                     
    :table-header           (material-ui :TableHeader)                     
    :table-header-column    (material-ui :TableHeaderColumn)               
    :table-row              (material-ui :TableRow)                        
    :table-row-column       (material-ui :TableRowColumn)                  
    :tabs                   (material-ui :Tabs)                            
    :text-field             (material-ui :TextField)                       
    :time-picker            (material-ui :TimePicker)                      
    :toggle                 (material-ui :Toggle)                          
    :toolbar                (material-ui :Toolbar)                         
    :toolbar-group          (material-ui :ToolbarGroup)                    
    :toolbar-separator      (material-ui :ToolbarSeparator)                
    :toolbar-title          (material-ui :ToolbarTitle)
    }))

(def ^:private material-ui-icons
  {:action-accessibility                               ic/action-accessibility
   :action-accessible                                  ic/action-accessible
   :action-account-balance-wallet                      ic/action-account-balance-wallet
   :action-account-balance                             ic/action-account-balance
   :action-account-box                                 ic/action-account-box
   :action-account-circle                              ic/action-account-circle
   :action-add-shopping-cart                           ic/action-add-shopping-cart
   :action-alarm-add                                   ic/action-alarm-add
   :action-alarm-off                                   ic/action-alarm-off
   :action-alarm-on                                    ic/action-alarm-on
   :action-alarm                                       ic/action-alarm
   :action-all-out                                     ic/action-all-out
   :action-android                                     ic/action-android
   :action-announcement                                ic/action-announcement
   :action-aspect-ratio                                ic/action-aspect-ratio
   :action-assessment                                  ic/action-assessment
   :action-assignment-ind                              ic/action-assignment-ind
   :action-assignment-late                             ic/action-assignment-late
   :action-assignment-return                           ic/action-assignment-return
   :action-assignment-returned                         ic/action-assignment-returned
   :action-assignment-turned-in                        ic/action-assignment-turned-in
   :action-assignment                                  ic/action-assignment
   :action-autorenew                                   ic/action-autorenew
   :action-backup                                      ic/action-backup
   :action-book                                        ic/action-book
   :action-bookmark-border                             ic/action-bookmark-border
   :action-bookmark                                    ic/action-bookmark
   :action-bug-report                                  ic/action-bug-report
   :action-build                                       ic/action-build
   :action-cached                                      ic/action-cached
   :action-camera-enhance                              ic/action-camera-enhance
   :action-card-giftcard                               ic/action-card-giftcard
   :action-card-membership                             ic/action-card-membership
   :action-card-travel                                 ic/action-card-travel
   :action-change-history                              ic/action-change-history
   :action-check-circle                                ic/action-check-circle
   :action-chrome-reader-mode                          ic/action-chrome-reader-mode
   :action-class                                       ic/action-class
   :action-code                                        ic/action-code
   :action-compare-arrows                              ic/action-compare-arrows
   :action-copyright                                   ic/action-copyright
   :action-credit-card                                 ic/action-credit-card
   :action-dashboard                                   ic/action-dashboard
   :action-date-range                                  ic/action-date-range
   :action-delete-forever                              ic/action-delete-forever
   :action-delete                                      ic/action-delete
   :action-description                                 ic/action-description
   :action-dns                                         ic/action-dns
   :action-done-all                                    ic/action-done-all
   :action-done                                        ic/action-done
   :action-donut-large                                 ic/action-donut-large
   :action-donut-small                                 ic/action-donut-small
   :action-eject                                       ic/action-eject
   :action-euro-symbol                                 ic/action-euro-symbol
   :action-event-seat                                  ic/action-event-seat
   :action-event                                       ic/action-event
   :action-exit-to-app                                 ic/action-exit-to-app
   :action-explore                                     ic/action-explore
   :action-extension                                   ic/action-extension
   :action-face                                        ic/action-face
   :action-favorite-border                             ic/action-favorite-border
   :action-favorite                                    ic/action-favorite
   :action-feedback                                    ic/action-feedback
   :action-find-in-page                                ic/action-find-in-page
   :action-find-replace                                ic/action-find-replace
   :action-fingerprint                                 ic/action-fingerprint
   :action-flight-land                                 ic/action-flight-land
   :action-flight-takeoff                              ic/action-flight-takeoff
   :action-flip-to-back                                ic/action-flip-to-back
   :action-flip-to-front                               ic/action-flip-to-front
   :action-g-translate                                 ic/action-g-translate
   :action-gavel                                       ic/action-gavel
   :action-get-app                                     ic/action-get-app
   :action-gif                                         ic/action-gif
   :action-grade                                       ic/action-grade
   :action-group-work                                  ic/action-group-work
   :action-help-outline                                ic/action-help-outline
   :action-help                                        ic/action-help
   :action-highlight-off                               ic/action-highlight-off
   :action-history                                     ic/action-history
   :action-home                                        ic/action-home
   :action-hourglass-empty                             ic/action-hourglass-empty
   :action-hourglass-full                              ic/action-hourglass-full
   :action-http                                        ic/action-http
   :action-https                                       ic/action-https
   :action-important-devices                           ic/action-important-devices
   :action-info-outline                                ic/action-info-outline
   :action-info                                        ic/action-info
   :action-input                                       ic/action-input
   :action-invert-colors                               ic/action-invert-colors
   :action-label-outline                               ic/action-label-outline
   :action-label                                       ic/action-label
   :action-language                                    ic/action-language
   :action-launch                                      ic/action-launch
   :action-lightbulb-outline                           ic/action-lightbulb-outline
   :action-line-style                                  ic/action-line-style
   :action-line-weight                                 ic/action-line-weight
   :action-list                                        ic/action-list
   :action-lock-open                                   ic/action-lock-open
   :action-lock-outline                                ic/action-lock-outline
   :action-lock                                        ic/action-lock
   :action-loyalty                                     ic/action-loyalty
   :action-markunread-mailbox                          ic/action-markunread-mailbox
   :action-motorcycle                                  ic/action-motorcycle
   :action-note-add                                    ic/action-note-add
   :action-offline-pin                                 ic/action-offline-pin
   :action-opacity                                     ic/action-opacity
   :action-open-in-browser                             ic/action-open-in-browser
   :action-open-in-new                                 ic/action-open-in-new
   :action-open-with                                   ic/action-open-with
   :action-pageview                                    ic/action-pageview
   :action-pan-tool                                    ic/action-pan-tool
   :action-payment                                     ic/action-payment
   :action-perm-camera-mic                             ic/action-perm-camera-mic
   :action-perm-contact-calendar                       ic/action-perm-contact-calendar
   :action-perm-data-setting                           ic/action-perm-data-setting
   :action-perm-device-information                     ic/action-perm-device-information
   :action-perm-identity                               ic/action-perm-identity
   :action-perm-media                                  ic/action-perm-media
   :action-perm-phone-msg                              ic/action-perm-phone-msg
   :action-perm-scan-wifi                              ic/action-perm-scan-wifi
   :action-pets                                        ic/action-pets
   :action-picture-in-picture-alt                      ic/action-picture-in-picture-alt
   :action-picture-in-picture                          ic/action-picture-in-picture
   :action-play-for-work                               ic/action-play-for-work
   :action-polymer                                     ic/action-polymer
   :action-power-settings-new                          ic/action-power-settings-new
   :action-pregnant-woman                              ic/action-pregnant-woman
   :action-print                                       ic/action-print
   :action-query-builder                               ic/action-query-builder
   :action-question-answer                             ic/action-question-answer
   :action-receipt                                     ic/action-receipt
   :action-record-voice-over                           ic/action-record-voice-over
   :action-redeem                                      ic/action-redeem
   :action-remove-shopping-cart                        ic/action-remove-shopping-cart
   :action-reorder                                     ic/action-reorder
   :action-report-problem                              ic/action-report-problem
   :action-restore-page                                ic/action-restore-page
   :action-restore                                     ic/action-restore
   :action-room                                        ic/action-room
   :action-rounded-corner                              ic/action-rounded-corner
   :action-rowing                                      ic/action-rowing
   :action-schedule                                    ic/action-schedule
   :action-search                                      ic/action-search
   :action-settings-applications                       ic/action-settings-applications
   :action-settings-backup-restore                     ic/action-settings-backup-restore
   :action-settings-bluetooth                          ic/action-settings-bluetooth
   :action-settings-brightness                         ic/action-settings-brightness
   :action-settings-cell                               ic/action-settings-cell
   :action-settings-ethernet                           ic/action-settings-ethernet
   :action-settings-input-antenna                      ic/action-settings-input-antenna
   :action-settings-input-component                    ic/action-settings-input-component
   :action-settings-input-composite                    ic/action-settings-input-composite
   :action-settings-input-hdmi                         ic/action-settings-input-hdmi
   :action-settings-input-svideo                       ic/action-settings-input-svideo
   :action-settings-overscan                           ic/action-settings-overscan
   :action-settings-phone                              ic/action-settings-phone
   :action-settings-power                              ic/action-settings-power
   :action-settings-remote                             ic/action-settings-remote
   :action-settings-voice                              ic/action-settings-voice
   :action-settings                                    ic/action-settings
   :action-shop-two                                    ic/action-shop-two
   :action-shop                                        ic/action-shop
   :action-shopping-basket                             ic/action-shopping-basket
   :action-shopping-cart                               ic/action-shopping-cart
   :action-speaker-notes-off                           ic/action-speaker-notes-off
   :action-speaker-notes                               ic/action-speaker-notes
   :action-spellcheck                                  ic/action-spellcheck
   :action-stars                                       ic/action-stars
   :action-store                                       ic/action-store
   :action-subject                                     ic/action-subject
   :action-supervisor-account                          ic/action-supervisor-account
   :action-swap-horiz                                  ic/action-swap-horiz
   :action-swap-vert                                   ic/action-swap-vert
   :action-swap-vertical-circle                        ic/action-swap-vertical-circle
   :action-system-update-alt                           ic/action-system-update-alt
   :action-tab-unselected                              ic/action-tab-unselected
   :action-tab                                         ic/action-tab
   :action-theaters                                    ic/action-theaters
   :action-three-d-rotation                            ic/action-three-d-rotation
   :action-thumb-down                                  ic/action-thumb-down
   :action-thumb-up                                    ic/action-thumb-up
   :action-thumbs-up-down                              ic/action-thumbs-up-down
   :action-timeline                                    ic/action-timeline
   :action-toc                                         ic/action-toc
   :action-today                                       ic/action-today
   :action-toll                                        ic/action-toll
   :action-touch-app                                   ic/action-touch-app
   :action-track-changes                               ic/action-track-changes
   :action-translate                                   ic/action-translate
   :action-trending-down                               ic/action-trending-down
   :action-trending-flat                               ic/action-trending-flat
   :action-trending-up                                 ic/action-trending-up
   :action-turned-in-not                               ic/action-turned-in-not
   :action-turned-in                                   ic/action-turned-in
   :action-update                                      ic/action-update
   :action-verified-user                               ic/action-verified-user
   :action-view-agenda                                 ic/action-view-agenda
   :action-view-array                                  ic/action-view-array
   :action-view-carousel                               ic/action-view-carousel
   :action-view-column                                 ic/action-view-column
   :action-view-day                                    ic/action-view-day
   :action-view-headline                               ic/action-view-headline
   :action-view-list                                   ic/action-view-list
   :action-view-module                                 ic/action-view-module
   :action-view-quilt                                  ic/action-view-quilt
   :action-view-stream                                 ic/action-view-stream
   :action-view-week                                   ic/action-view-week
   :action-visibility-off                              ic/action-visibility-off
   :action-visibility                                  ic/action-visibility
   :action-watch-later                                 ic/action-watch-later
   :action-work                                        ic/action-work
   :action-youtube-searched-for                        ic/action-youtube-searched-for
   :action-zoom-in                                     ic/action-zoom-in
   :action-zoom-out                                    ic/action-zoom-out
   :alert-add-alert                                    ic/alert-add-alert
   :alert-error-outline                                ic/alert-error-outline
   :alert-error                                        ic/alert-error
   :alert-warning                                      ic/alert-warning
   :av-add-to-queue                                    ic/av-add-to-queue
   :av-airplay                                         ic/av-airplay
   :av-album                                           ic/av-album
   :av-art-track                                       ic/av-art-track
   :av-av-timer                                        ic/av-av-timer
   :av-branding-watermark                              ic/av-branding-watermark
   :av-call-to-action                                  ic/av-call-to-action
   :av-closed-caption                                  ic/av-closed-caption
   :av-equalizer                                       ic/av-equalizer
   :av-explicit                                        ic/av-explicit
   :av-fast-forward                                    ic/av-fast-forward
   :av-fast-rewind                                     ic/av-fast-rewind
   :av-featured-play-list                              ic/av-featured-play-list
   :av-featured-video                                  ic/av-featured-video
   :av-fiber-dvr                                       ic/av-fiber-dvr
   :av-fiber-manual-record                             ic/av-fiber-manual-record
   :av-fiber-new                                       ic/av-fiber-new
   :av-fiber-pin                                       ic/av-fiber-pin
   :av-fiber-smart-record                              ic/av-fiber-smart-record
   :av-forward-1-0                                     ic/av-forward-1-0
   :av-forward-3-0                                     ic/av-forward-3-0
   :av-forward-5                                       ic/av-forward-5
   :av-games                                           ic/av-games
   :av-hd                                              ic/av-hd
   :av-hearing                                         ic/av-hearing
   :av-high-quality                                    ic/av-high-quality
   :av-library-add                                     ic/av-library-add
   :av-library-books                                   ic/av-library-books
   :av-library-music                                   ic/av-library-music
   :av-loop                                            ic/av-loop
   :av-mic-none                                        ic/av-mic-none
   :av-mic-off                                         ic/av-mic-off
   :av-mic                                             ic/av-mic
   :av-movie                                           ic/av-movie
   :av-music-video                                     ic/av-music-video
   :av-new-releases                                    ic/av-new-releases
   :av-not-interested                                  ic/av-not-interested
   :av-note                                            ic/av-note
   :av-pause-circle-filled                             ic/av-pause-circle-filled
   :av-pause-circle-outline                            ic/av-pause-circle-outline
   :av-pause                                           ic/av-pause
   :av-play-arrow                                      ic/av-play-arrow
   :av-play-circle-filled                              ic/av-play-circle-filled
   :av-play-circle-outline                             ic/av-play-circle-outline
   :av-playlist-add-check                              ic/av-playlist-add-check
   :av-playlist-add                                    ic/av-playlist-add
   :av-playlist-play                                   ic/av-playlist-play
   :av-queue-music                                     ic/av-queue-music
   :av-queue-play-next                                 ic/av-queue-play-next
   :av-queue                                           ic/av-queue
   :av-radio                                           ic/av-radio
   :av-recent-actors                                   ic/av-recent-actors
   :av-remove-from-queue                               ic/av-remove-from-queue
   :av-repeat-one                                      ic/av-repeat-one
   :av-repeat                                          ic/av-repeat
   :av-replay-1-0                                      ic/av-replay-1-0
   :av-replay-3-0                                      ic/av-replay-3-0
   :av-replay-5                                        ic/av-replay-5
   :av-replay                                          ic/av-replay
   :av-shuffle                                         ic/av-shuffle
   :av-skip-next                                       ic/av-skip-next
   :av-skip-previous                                   ic/av-skip-previous
   :av-slow-motion-video                               ic/av-slow-motion-video
   :av-snooze                                          ic/av-snooze
   :av-sort-by-alpha                                   ic/av-sort-by-alpha
   :av-stop                                            ic/av-stop
   :av-subscriptions                                   ic/av-subscriptions
   :av-subtitles                                       ic/av-subtitles
   :av-surround-sound                                  ic/av-surround-sound
   :av-video-call                                      ic/av-video-call
   :av-video-label                                     ic/av-video-label
   :av-video-library                                   ic/av-video-library
   :av-videocam-off                                    ic/av-videocam-off
   :av-videocam                                        ic/av-videocam
   :av-volume-down                                     ic/av-volume-down
   :av-volume-mute                                     ic/av-volume-mute
   :av-volume-off                                      ic/av-volume-off
   :av-volume-up                                       ic/av-volume-up
   :av-web-asset                                       ic/av-web-asset
   :av-web                                             ic/av-web
   :communication-business                             ic/communication-business
   :communication-call-end                             ic/communication-call-end
   :communication-call-made                            ic/communication-call-made
   :communication-call-merge                           ic/communication-call-merge
   :communication-call-missed-outgoing                 ic/communication-call-missed-outgoing
   :communication-call-missed                          ic/communication-call-missed
   :communication-call-received                        ic/communication-call-received
   :communication-call-split                           ic/communication-call-split
   :communication-call                                 ic/communication-call
   :communication-chat-bubble-outline                  ic/communication-chat-bubble-outline
   :communication-chat-bubble                          ic/communication-chat-bubble
   :communication-chat                                 ic/communication-chat
   :communication-clear-all                            ic/communication-clear-all
   :communication-comment                              ic/communication-comment
   :communication-contact-mail                         ic/communication-contact-mail
   :communication-contact-phone                        ic/communication-contact-phone
   :communication-contacts                             ic/communication-contacts
   :communication-dialer-sip                           ic/communication-dialer-sip
   :communication-dialpad                              ic/communication-dialpad
   :communication-email                                ic/communication-email
   :communication-forum                                ic/communication-forum
   :communication-import-contacts                      ic/communication-import-contacts
   :communication-import-export                        ic/communication-import-export
   :communication-invert-colors-off                    ic/communication-invert-colors-off
   :communication-live-help                            ic/communication-live-help
   :communication-location-off                         ic/communication-location-off
   :communication-location-on                          ic/communication-location-on
   :communication-mail-outline                         ic/communication-mail-outline
   :communication-message                              ic/communication-message
   :communication-no-sim                               ic/communication-no-sim
   :communication-phone                                ic/communication-phone
   :communication-phonelink-erase                      ic/communication-phonelink-erase
   :communication-phonelink-lock                       ic/communication-phonelink-lock
   :communication-phonelink-ring                       ic/communication-phonelink-ring
   :communication-phonelink-setup                      ic/communication-phonelink-setup
   :communication-portable-wifi-off                    ic/communication-portable-wifi-off
   :communication-present-to-all                       ic/communication-present-to-all
   :communication-ring-volume                          ic/communication-ring-volume
   :communication-rss-feed                             ic/communication-rss-feed
   :communication-screen-share                         ic/communication-screen-share
   :communication-speaker-phone                        ic/communication-speaker-phone
   :communication-stay-current-landscape               ic/communication-stay-current-landscape
   :communication-stay-current-portrait                ic/communication-stay-current-portrait
   :communication-stay-primary-landscape               ic/communication-stay-primary-landscape
   :communication-stay-primary-portrait                ic/communication-stay-primary-portrait
   :communication-stop-screen-share                    ic/communication-stop-screen-share
   :communication-swap-calls                           ic/communication-swap-calls
   :communication-textsms                              ic/communication-textsms
   :communication-voicemail                            ic/communication-voicemail
   :communication-vpn-key                              ic/communication-vpn-key
   :content-add-box                                    ic/content-add-box
   :content-add-circle-outline                         ic/content-add-circle-outline
   :content-add-circle                                 ic/content-add-circle
   :content-add                                        ic/content-add
   :content-archive                                    ic/content-archive
   :content-backspace                                  ic/content-backspace
   :content-block                                      ic/content-block
   :content-clear                                      ic/content-clear
   :content-content-copy                               ic/content-content-copy
   :content-content-cut                                ic/content-content-cut
   :content-content-paste                              ic/content-content-paste
   :content-create                                     ic/content-create
   :content-delete-sweep                               ic/content-delete-sweep
   :content-drafts                                     ic/content-drafts
   :content-filter-list                                ic/content-filter-list
   :content-flag                                       ic/content-flag
   :content-font-download                              ic/content-font-download
   :content-forward                                    ic/content-forward
   :content-gesture                                    ic/content-gesture
   :content-inbox                                      ic/content-inbox
   :content-link                                       ic/content-link
   :content-low-priority                               ic/content-low-priority
   :content-mail                                       ic/content-mail
   :content-markunread                                 ic/content-markunread
   :content-move-to-inbox                              ic/content-move-to-inbox
   :content-next-week                                  ic/content-next-week
   :content-redo                                       ic/content-redo
   :content-remove-circle-outline                      ic/content-remove-circle-outline
   :content-remove-circle                              ic/content-remove-circle
   :content-remove                                     ic/content-remove
   :content-reply-all                                  ic/content-reply-all
   :content-reply                                      ic/content-reply
   :content-report                                     ic/content-report
   :content-save                                       ic/content-save
   :content-select-all                                 ic/content-select-all
   :content-send                                       ic/content-send
   :content-sort                                       ic/content-sort
   :content-text-format                                ic/content-text-format
   :content-unarchive                                  ic/content-unarchive
   :content-undo                                       ic/content-undo
   :content-weekend                                    ic/content-weekend
   :device-access-alarm                                ic/device-access-alarm
   :device-access-alarms                               ic/device-access-alarms
   :device-access-time                                 ic/device-access-time
   :device-add-alarm                                   ic/device-add-alarm
   :device-airplanemode-active                         ic/device-airplanemode-active
   :device-airplanemode-inactive                       ic/device-airplanemode-inactive
   :device-battery-2-0                                 ic/device-battery-2-0
   :device-battery-3-0                                 ic/device-battery-3-0
   :device-battery-5-0                                 ic/device-battery-5-0
   :device-battery-6-0                                 ic/device-battery-6-0
   :device-battery-8-0                                 ic/device-battery-8-0
   :device-battery-9-0                                 ic/device-battery-9-0
   :device-battery-alert                               ic/device-battery-alert
   :device-battery-charging-2-0                        ic/device-battery-charging-2-0
   :device-battery-charging-3-0                        ic/device-battery-charging-3-0
   :device-battery-charging-5-0                        ic/device-battery-charging-5-0
   :device-battery-charging-6-0                        ic/device-battery-charging-6-0
   :device-battery-charging-8-0                        ic/device-battery-charging-8-0
   :device-battery-charging-9-0                        ic/device-battery-charging-9-0
   :device-battery-charging-full                       ic/device-battery-charging-full
   :device-battery-full                                ic/device-battery-full
   :device-battery-std                                 ic/device-battery-std
   :device-battery-unknown                             ic/device-battery-unknown
   :device-bluetooth-connected                         ic/device-bluetooth-connected
   :device-bluetooth-disabled                          ic/device-bluetooth-disabled
   :device-bluetooth-searching                         ic/device-bluetooth-searching
   :device-bluetooth                                   ic/device-bluetooth
   :device-brightness-auto                             ic/device-brightness-auto
   :device-brightness-high                             ic/device-brightness-high
   :device-brightness-low                              ic/device-brightness-low
   :device-brightness-medium                           ic/device-brightness-medium
   :device-data-usage                                  ic/device-data-usage
   :device-developer-mode                              ic/device-developer-mode
   :device-devices                                     ic/device-devices
   :device-dvr                                         ic/device-dvr
   :device-gps-fixed                                   ic/device-gps-fixed
   :device-gps-not-fixed                               ic/device-gps-not-fixed
   :device-gps-off                                     ic/device-gps-off
   :device-graphic-eq                                  ic/device-graphic-eq
   :device-location-disabled                           ic/device-location-disabled
   :device-location-searching                          ic/device-location-searching
   :device-network-cell                                ic/device-network-cell
   :device-network-wifi                                ic/device-network-wifi
   :device-nfc                                         ic/device-nfc
   :device-screen-lock-landscape                       ic/device-screen-lock-landscape
   :device-screen-lock-portrait                        ic/device-screen-lock-portrait
   :device-screen-lock-rotation                        ic/device-screen-lock-rotation
   :device-screen-rotation                             ic/device-screen-rotation
   :device-sd-storage                                  ic/device-sd-storage
   :device-settings-system-daydream                    ic/device-settings-system-daydream
   :device-signal-cellular-0-bar                       ic/device-signal-cellular-0-bar
   :device-signal-cellular-1-bar                       ic/device-signal-cellular-1-bar
   :device-signal-cellular-2-bar                       ic/device-signal-cellular-2-bar
   :device-signal-cellular-3-bar                       ic/device-signal-cellular-3-bar
   :device-signal-cellular-4-bar                       ic/device-signal-cellular-4-bar
   :device-signal-cellular-connected-no-internet-0-bar ic/device-signal-cellular-connected-no-internet-0-bar
   :device-signal-cellular-connected-no-internet-1-bar ic/device-signal-cellular-connected-no-internet-1-bar
   :device-signal-cellular-connected-no-internet-2-bar ic/device-signal-cellular-connected-no-internet-2-bar
   :device-signal-cellular-connected-no-internet-3-bar ic/device-signal-cellular-connected-no-internet-3-bar
   :device-signal-cellular-connected-no-internet-4-bar ic/device-signal-cellular-connected-no-internet-4-bar
   :device-signal-cellular-no-sim                      ic/device-signal-cellular-no-sim
   :device-signal-cellular-null                        ic/device-signal-cellular-null
   :device-signal-cellular-off                         ic/device-signal-cellular-off
   :device-signal-wifi-0-bar                           ic/device-signal-wifi-0-bar
   :device-signal-wifi-1-bar-lock                      ic/device-signal-wifi-1-bar-lock
   :device-signal-wifi-1-bar                           ic/device-signal-wifi-1-bar
   :device-signal-wifi-2-bar-lock                      ic/device-signal-wifi-2-bar-lock
   :device-signal-wifi-2-bar                           ic/device-signal-wifi-2-bar
   :device-signal-wifi-3-bar-lock                      ic/device-signal-wifi-3-bar-lock
   :device-signal-wifi-3-bar                           ic/device-signal-wifi-3-bar
   :device-signal-wifi-4-bar-lock                      ic/device-signal-wifi-4-bar-lock
   :device-signal-wifi-4-bar                           ic/device-signal-wifi-4-bar
   :device-signal-wifi-off                             ic/device-signal-wifi-off
   :device-storage                                     ic/device-storage
   :device-usb                                         ic/device-usb
   :device-wallpaper                                   ic/device-wallpaper
   :device-widgets                                     ic/device-widgets
   :device-wifi-lock                                   ic/device-wifi-lock
   :device-wifi-tethering                              ic/device-wifi-tethering
   :editor-attach-file                                 ic/editor-attach-file
   :editor-attach-money                                ic/editor-attach-money
   :editor-border-all                                  ic/editor-border-all
   :editor-border-bottom                               ic/editor-border-bottom
   :editor-border-clear                                ic/editor-border-clear
   :editor-border-color                                ic/editor-border-color
   :editor-border-horizontal                           ic/editor-border-horizontal
   :editor-border-inner                                ic/editor-border-inner
   :editor-border-left                                 ic/editor-border-left
   :editor-border-outer                                ic/editor-border-outer
   :editor-border-right                                ic/editor-border-right
   :editor-border-style                                ic/editor-border-style
   :editor-border-top                                  ic/editor-border-top
   :editor-border-vertical                             ic/editor-border-vertical
   :editor-bubble-chart                                ic/editor-bubble-chart
   :editor-drag-handle                                 ic/editor-drag-handle
   :editor-format-align-center                         ic/editor-format-align-center
   :editor-format-align-justify                        ic/editor-format-align-justify
   :editor-format-align-left                           ic/editor-format-align-left
   :editor-format-align-right                          ic/editor-format-align-right
   :editor-format-bold                                 ic/editor-format-bold
   :editor-format-clear                                ic/editor-format-clear
   :editor-format-color-fill                           ic/editor-format-color-fill
   :editor-format-color-reset                          ic/editor-format-color-reset
   :editor-format-color-text                           ic/editor-format-color-text
   :editor-format-indent-decrease                      ic/editor-format-indent-decrease
   :editor-format-indent-increase                      ic/editor-format-indent-increase
   :editor-format-italic                               ic/editor-format-italic
   :editor-format-line-spacing                         ic/editor-format-line-spacing
   :editor-format-list-bulleted                        ic/editor-format-list-bulleted
   :editor-format-list-numbered                        ic/editor-format-list-numbered
   :editor-format-paint                                ic/editor-format-paint
   :editor-format-quote                                ic/editor-format-quote
   :editor-format-shapes                               ic/editor-format-shapes
   :editor-format-size                                 ic/editor-format-size
   :editor-format-strikethrough                        ic/editor-format-strikethrough
   :editor-format-textdirection-l-to-r                 ic/editor-format-textdirection-l-to-r
   :editor-format-textdirection-r-to-l                 ic/editor-format-textdirection-r-to-l
   :editor-format-underlined                           ic/editor-format-underlined
   :editor-functions                                   ic/editor-functions
   :editor-highlight                                   ic/editor-highlight
   :editor-insert-chart                                ic/editor-insert-chart
   :editor-insert-comment                              ic/editor-insert-comment
   :editor-insert-drive-file                           ic/editor-insert-drive-file
   :editor-insert-emoticon                             ic/editor-insert-emoticon
   :editor-insert-invitation                           ic/editor-insert-invitation
   :editor-insert-link                                 ic/editor-insert-link
   :editor-insert-photo                                ic/editor-insert-photo
   :editor-linear-scale                                ic/editor-linear-scale
   :editor-merge-type                                  ic/editor-merge-type
   :editor-mode-comment                                ic/editor-mode-comment
   :editor-mode-edit                                   ic/editor-mode-edit
   :editor-monetization-on                             ic/editor-monetization-on
   :editor-money-off                                   ic/editor-money-off
   :editor-multiline-chart                             ic/editor-multiline-chart
   :editor-pie-chart-outlined                          ic/editor-pie-chart-outlined
   :editor-pie-chart                                   ic/editor-pie-chart
   :editor-publish                                     ic/editor-publish
   :editor-short-text                                  ic/editor-short-text
   :editor-show-chart                                  ic/editor-show-chart
   :editor-space-bar                                   ic/editor-space-bar
   :editor-strikethrough-s                             ic/editor-strikethrough-s
   :editor-text-fields                                 ic/editor-text-fields
   :editor-title                                       ic/editor-title
   :editor-vertical-align-bottom                       ic/editor-vertical-align-bottom
   :editor-vertical-align-center                       ic/editor-vertical-align-center
   :editor-vertical-align-top                          ic/editor-vertical-align-top
   :editor-wrap-text                                   ic/editor-wrap-text
   :file-attachment                                    ic/file-attachment
   :file-cloud-circle                                  ic/file-cloud-circle
   :file-cloud-done                                    ic/file-cloud-done
   :file-cloud-download                                ic/file-cloud-download
   :file-cloud-off                                     ic/file-cloud-off
   :file-cloud-queue                                   ic/file-cloud-queue
   :file-cloud-upload                                  ic/file-cloud-upload
   :file-cloud                                         ic/file-cloud
   :file-create-new-folder                             ic/file-create-new-folder
   :file-file-download                                 ic/file-file-download
   :file-file-upload                                   ic/file-file-upload
   :file-folder-open                                   ic/file-folder-open
   :file-folder-shared                                 ic/file-folder-shared
   :file-folder                                        ic/file-folder
   :hardware-cast-connected                            ic/hardware-cast-connected
   :hardware-cast                                      ic/hardware-cast
   :hardware-computer                                  ic/hardware-computer
   :hardware-desktop-mac                               ic/hardware-desktop-mac
   :hardware-desktop-windows                           ic/hardware-desktop-windows
   :hardware-developer-board                           ic/hardware-developer-board
   :hardware-device-hub                                ic/hardware-device-hub
   :hardware-devices-other                             ic/hardware-devices-other
   :hardware-dock                                      ic/hardware-dock
   :hardware-gamepad                                   ic/hardware-gamepad
   :hardware-headset-mic                               ic/hardware-headset-mic
   :hardware-headset                                   ic/hardware-headset
   :hardware-keyboard-arrow-down                       ic/hardware-keyboard-arrow-down
   :hardware-keyboard-arrow-left                       ic/hardware-keyboard-arrow-left
   :hardware-keyboard-arrow-right                      ic/hardware-keyboard-arrow-right
   :hardware-keyboard-arrow-up                         ic/hardware-keyboard-arrow-up
   :hardware-keyboard-backspace                        ic/hardware-keyboard-backspace
   :hardware-keyboard-capslock                         ic/hardware-keyboard-capslock
   :hardware-keyboard-hide                             ic/hardware-keyboard-hide
   :hardware-keyboard-return                           ic/hardware-keyboard-return
   :hardware-keyboard-tab                              ic/hardware-keyboard-tab
   :hardware-keyboard-voice                            ic/hardware-keyboard-voice
   :hardware-keyboard                                  ic/hardware-keyboard
   :hardware-laptop-chromebook                         ic/hardware-laptop-chromebook
   :hardware-laptop-mac                                ic/hardware-laptop-mac
   :hardware-laptop-windows                            ic/hardware-laptop-windows
   :hardware-laptop                                    ic/hardware-laptop
   :hardware-memory                                    ic/hardware-memory
   :hardware-mouse                                     ic/hardware-mouse
   :hardware-phone-android                             ic/hardware-phone-android
   :hardware-phone-iphone                              ic/hardware-phone-iphone
   :hardware-phonelink-off                             ic/hardware-phonelink-off
   :hardware-phonelink                                 ic/hardware-phonelink
   :hardware-power-input                               ic/hardware-power-input
   :hardware-router                                    ic/hardware-router
   :hardware-scanner                                   ic/hardware-scanner
   :hardware-security                                  ic/hardware-security
   :hardware-sim-card                                  ic/hardware-sim-card
   :hardware-smartphone                                ic/hardware-smartphone
   :hardware-speaker-group                             ic/hardware-speaker-group
   :hardware-speaker                                   ic/hardware-speaker
   :hardware-tablet-android                            ic/hardware-tablet-android
   :hardware-tablet-mac                                ic/hardware-tablet-mac
   :hardware-tablet                                    ic/hardware-tablet
   :hardware-toys                                      ic/hardware-toys
   :hardware-tv                                        ic/hardware-tv
   :hardware-videogame-asset                           ic/hardware-videogame-asset
   :hardware-watch                                     ic/hardware-watch
   :image-add-a-photo                                  ic/image-add-a-photo
   :image-add-to-photos                                ic/image-add-to-photos
   :image-adjust                                       ic/image-adjust
   :image-assistant-photo                              ic/image-assistant-photo
   :image-assistant                                    ic/image-assistant
   :image-audiotrack                                   ic/image-audiotrack
   :image-blur-circular                                ic/image-blur-circular
   :image-blur-linear                                  ic/image-blur-linear
   :image-blur-off                                     ic/image-blur-off
   :image-blur-on                                      ic/image-blur-on
   :image-brightness-1                                 ic/image-brightness-1
   :image-brightness-2                                 ic/image-brightness-2
   :image-brightness-3                                 ic/image-brightness-3
   :image-brightness-4                                 ic/image-brightness-4
   :image-brightness-5                                 ic/image-brightness-5
   :image-brightness-6                                 ic/image-brightness-6
   :image-brightness-7                                 ic/image-brightness-7
   :image-broken-image                                 ic/image-broken-image
   :image-brush                                        ic/image-brush
   :image-burst-mode                                   ic/image-burst-mode
   :image-camera-alt                                   ic/image-camera-alt
   :image-camera-front                                 ic/image-camera-front
   :image-camera-rear                                  ic/image-camera-rear
   :image-camera-roll                                  ic/image-camera-roll
   :image-camera                                       ic/image-camera
   :image-center-focus-strong                          ic/image-center-focus-strong
   :image-center-focus-weak                            ic/image-center-focus-weak
   :image-collections-bookmark                         ic/image-collections-bookmark
   :image-collections                                  ic/image-collections
   :image-color-lens                                   ic/image-color-lens
   :image-colorize                                     ic/image-colorize
   :image-compare                                      ic/image-compare
   :image-control-point-duplicate                      ic/image-control-point-duplicate
   :image-control-point                                ic/image-control-point
   :image-crop-1-6-9                                   ic/image-crop-1-6-9
   :image-crop-3-2                                     ic/image-crop-3-2
   :image-crop-5-4                                     ic/image-crop-5-4
   :image-crop-7-5                                     ic/image-crop-7-5
   :image-crop-din                                     ic/image-crop-din
   :image-crop-free                                    ic/image-crop-free
   :image-crop-landscape                               ic/image-crop-landscape
   :image-crop-original                                ic/image-crop-original
   :image-crop-portrait                                ic/image-crop-portrait
   :image-crop-rotate                                  ic/image-crop-rotate
   :image-crop-square                                  ic/image-crop-square
   :image-crop                                         ic/image-crop
   :image-dehaze                                       ic/image-dehaze
   :image-details                                      ic/image-details
   :image-edit                                         ic/image-edit
   :image-exposure-neg-1                               ic/image-exposure-neg-1
   :image-exposure-neg-2                               ic/image-exposure-neg-2
   :image-exposure-plus-1                              ic/image-exposure-plus-1
   :image-exposure-plus-2                              ic/image-exposure-plus-2
   :image-exposure-zero                                ic/image-exposure-zero
   :image-exposure                                     ic/image-exposure
   :image-filter-1                                     ic/image-filter-1
   :image-filter-2                                     ic/image-filter-2
   :image-filter-3                                     ic/image-filter-3
   :image-filter-4                                     ic/image-filter-4
   :image-filter-5                                     ic/image-filter-5
   :image-filter-6                                     ic/image-filter-6
   :image-filter-7                                     ic/image-filter-7
   :image-filter-8                                     ic/image-filter-8
   :image-filter-9-plus                                ic/image-filter-9-plus
   :image-filter-9                                     ic/image-filter-9
   :image-filter-b-and-w                               ic/image-filter-b-and-w
   :image-filter-center-focus                          ic/image-filter-center-focus
   :image-filter-drama                                 ic/image-filter-drama
   :image-filter-frames                                ic/image-filter-frames
   :image-filter-hdr                                   ic/image-filter-hdr
   :image-filter-none                                  ic/image-filter-none
   :image-filter-tilt-shift                            ic/image-filter-tilt-shift
   :image-filter-vintage                               ic/image-filter-vintage
   :image-filter                                       ic/image-filter
   :image-flare                                        ic/image-flare
   :image-flash-auto                                   ic/image-flash-auto
   :image-flash-off                                    ic/image-flash-off
   :image-flash-on                                     ic/image-flash-on
   :image-flip                                         ic/image-flip
   :image-gradient                                     ic/image-gradient
   :image-grain                                        ic/image-grain
   :image-grid-off                                     ic/image-grid-off
   :image-grid-on                                      ic/image-grid-on
   :image-hdr-off                                      ic/image-hdr-off
   :image-hdr-on                                       ic/image-hdr-on
   :image-hdr-strong                                   ic/image-hdr-strong
   :image-hdr-weak                                     ic/image-hdr-weak
   :image-healing                                      ic/image-healing
   :image-image-aspect-ratio                           ic/image-image-aspect-ratio
   :image-image                                        ic/image-image
   :image-iso                                          ic/image-iso
   :image-landscape                                    ic/image-landscape
   :image-leak-add                                     ic/image-leak-add
   :image-leak-remove                                  ic/image-leak-remove
   :image-lens                                         ic/image-lens
   :image-linked-camera                                ic/image-linked-camera
   :image-looks-3                                      ic/image-looks-3
   :image-looks-4                                      ic/image-looks-4
   :image-looks-5                                      ic/image-looks-5
   :image-looks-6                                      ic/image-looks-6
   :image-looks-one                                    ic/image-looks-one
   :image-looks-two                                    ic/image-looks-two
   :image-looks                                        ic/image-looks
   :image-loupe                                        ic/image-loupe
   :image-monochrome-photos                            ic/image-monochrome-photos
   :image-movie-creation                               ic/image-movie-creation
   :image-movie-filter                                 ic/image-movie-filter
   :image-music-note                                   ic/image-music-note
   :image-nature-people                                ic/image-nature-people
   :image-nature                                       ic/image-nature
   :image-navigate-before                              ic/image-navigate-before
   :image-navigate-next                                ic/image-navigate-next
   :image-palette                                      ic/image-palette
   :image-panorama-fish-eye                            ic/image-panorama-fish-eye
   :image-panorama-horizontal                          ic/image-panorama-horizontal
   :image-panorama-vertical                            ic/image-panorama-vertical
   :image-panorama-wide-angle                          ic/image-panorama-wide-angle
   :image-panorama                                     ic/image-panorama
   :image-photo-album                                  ic/image-photo-album
   :image-photo-camera                                 ic/image-photo-camera
   :image-photo-filter                                 ic/image-photo-filter
   :image-photo-library                                ic/image-photo-library
   :image-photo-size-select-actual                     ic/image-photo-size-select-actual
   :image-photo-size-select-large                      ic/image-photo-size-select-large
   :image-photo-size-select-small                      ic/image-photo-size-select-small
   :image-photo                                        ic/image-photo
   :image-picture-as-pdf                               ic/image-picture-as-pdf
   :image-portrait                                     ic/image-portrait
   :image-remove-red-eye                               ic/image-remove-red-eye
   :image-rotate-9-0-degrees-ccw                       ic/image-rotate-9-0-degrees-ccw
   :image-rotate-left                                  ic/image-rotate-left
   :image-rotate-right                                 ic/image-rotate-right
   :image-slideshow                                    ic/image-slideshow
   :image-straighten                                   ic/image-straighten
   :image-style                                        ic/image-style
   :image-switch-camera                                ic/image-switch-camera
   :image-switch-video                                 ic/image-switch-video
   :image-tag-faces                                    ic/image-tag-faces
   :image-texture                                      ic/image-texture
   :image-timelapse                                    ic/image-timelapse
   :image-timer-1-0                                    ic/image-timer-1-0
   :image-timer-3                                      ic/image-timer-3
   :image-timer-off                                    ic/image-timer-off
   :image-timer                                        ic/image-timer
   :image-tonality                                     ic/image-tonality
   :image-transform                                    ic/image-transform
   :image-tune                                         ic/image-tune
   :image-view-comfy                                   ic/image-view-comfy
   :image-view-compact                                 ic/image-view-compact
   :image-vignette                                     ic/image-vignette
   :image-wb-auto                                      ic/image-wb-auto
   :image-wb-cloudy                                    ic/image-wb-cloudy
   :image-wb-incandescent                              ic/image-wb-incandescent
   :image-wb-iridescent                                ic/image-wb-iridescent
   :image-wb-sunny                                     ic/image-wb-sunny
   :maps-add-location                                  ic/maps-add-location
   :maps-beenhere                                      ic/maps-beenhere
   :maps-directions-bike                               ic/maps-directions-bike
   :maps-directions-boat                               ic/maps-directions-boat
   :maps-directions-bus                                ic/maps-directions-bus
   :maps-directions-car                                ic/maps-directions-car
   :maps-directions-railway                            ic/maps-directions-railway
   :maps-directions-run                                ic/maps-directions-run
   :maps-directions-subway                             ic/maps-directions-subway
   :maps-directions-transit                            ic/maps-directions-transit
   :maps-directions-walk                               ic/maps-directions-walk
   :maps-directions                                    ic/maps-directions
   :maps-edit-location                                 ic/maps-edit-location
   :maps-ev-station                                    ic/maps-ev-station
   :maps-flight                                        ic/maps-flight
   :maps-hotel                                         ic/maps-hotel
   :maps-layers-clear                                  ic/maps-layers-clear
   :maps-layers                                        ic/maps-layers
   :maps-local-activity                                ic/maps-local-activity
   :maps-local-airport                                 ic/maps-local-airport
   :maps-local-atm                                     ic/maps-local-atm
   :maps-local-bar                                     ic/maps-local-bar
   :maps-local-cafe                                    ic/maps-local-cafe
   :maps-local-car-wash                                ic/maps-local-car-wash
   :maps-local-convenience-store                       ic/maps-local-convenience-store
   :maps-local-dining                                  ic/maps-local-dining
   :maps-local-drink                                   ic/maps-local-drink
   :maps-local-florist                                 ic/maps-local-florist
   :maps-local-gas-station                             ic/maps-local-gas-station
   :maps-local-grocery-store                           ic/maps-local-grocery-store
   :maps-local-hospital                                ic/maps-local-hospital
   :maps-local-hotel                                   ic/maps-local-hotel
   :maps-local-laundry-service                         ic/maps-local-laundry-service
   :maps-local-library                                 ic/maps-local-library
   :maps-local-mall                                    ic/maps-local-mall
   :maps-local-movies                                  ic/maps-local-movies
   :maps-local-offer                                   ic/maps-local-offer
   :maps-local-parking                                 ic/maps-local-parking
   :maps-local-pharmacy                                ic/maps-local-pharmacy
   :maps-local-phone                                   ic/maps-local-phone
   :maps-local-pizza                                   ic/maps-local-pizza
   :maps-local-play                                    ic/maps-local-play
   :maps-local-post-office                             ic/maps-local-post-office
   :maps-local-printshop                               ic/maps-local-printshop
   :maps-local-see                                     ic/maps-local-see
   :maps-local-shipping                                ic/maps-local-shipping
   :maps-local-taxi                                    ic/maps-local-taxi
   :maps-map                                           ic/maps-map
   :maps-my-location                                   ic/maps-my-location
   :maps-navigation                                    ic/maps-navigation
   :maps-near-me                                       ic/maps-near-me
   :maps-person-pin-circle                             ic/maps-person-pin-circle
   :maps-person-pin                                    ic/maps-person-pin
   :maps-pin-drop                                      ic/maps-pin-drop
   :maps-place                                         ic/maps-place
   :maps-rate-review                                   ic/maps-rate-review
   :maps-restaurant-menu                               ic/maps-restaurant-menu
   :maps-restaurant                                    ic/maps-restaurant
   :maps-satellite                                     ic/maps-satellite
   :maps-store-mall-directory                          ic/maps-store-mall-directory
   :maps-streetview                                    ic/maps-streetview
   :maps-subway                                        ic/maps-subway
   :maps-terrain                                       ic/maps-terrain
   :maps-traffic                                       ic/maps-traffic
   :maps-train                                         ic/maps-train
   :maps-tram                                          ic/maps-tram
   :maps-transfer-within-a-station                     ic/maps-transfer-within-a-station
   :maps-zoom-out-map                                  ic/maps-zoom-out-map
   :navigation-apps                                    ic/navigation-apps
   :navigation-arrow-back                              ic/navigation-arrow-back
   :navigation-arrow-downward                          ic/navigation-arrow-downward
   :navigation-arrow-drop-down-circle                  ic/navigation-arrow-drop-down-circle
   :navigation-arrow-drop-down                         ic/navigation-arrow-drop-down
   :navigation-arrow-drop-up                           ic/navigation-arrow-drop-up
   :navigation-arrow-forward                           ic/navigation-arrow-forward
   :navigation-arrow-upward                            ic/navigation-arrow-upward
   :navigation-cancel                                  ic/navigation-cancel
   :navigation-check                                   ic/navigation-check
   :navigation-chevron-left                            ic/navigation-chevron-left
   :navigation-chevron-right                           ic/navigation-chevron-right
   :navigation-close                                   ic/navigation-close
   :navigation-expand-less                             ic/navigation-expand-less
   :navigation-expand-more                             ic/navigation-expand-more
   :navigation-first-page                              ic/navigation-first-page
   :navigation-fullscreen-exit                         ic/navigation-fullscreen-exit
   :navigation-fullscreen                              ic/navigation-fullscreen
   :navigation-last-page                               ic/navigation-last-page
   :navigation-menu                                    ic/navigation-menu
   :navigation-more-horiz                              ic/navigation-more-horiz
   :navigation-more-vert                               ic/navigation-more-vert
   :navigation-refresh                                 ic/navigation-refresh
   :navigation-subdirectory-arrow-left                 ic/navigation-subdirectory-arrow-left
   :navigation-subdirectory-arrow-right                ic/navigation-subdirectory-arrow-right
   :navigation-unfold-less                             ic/navigation-unfold-less
   :navigation-unfold-more                             ic/navigation-unfold-more
   :navigation-arrow-drop-right                        ic/navigation-arrow-drop-right
   :notification-adb                                   ic/notification-adb
   :notification-airline-seat-flat-angled              ic/notification-airline-seat-flat-angled
   :notification-airline-seat-flat                     ic/notification-airline-seat-flat
   :notification-airline-seat-individual-suite         ic/notification-airline-seat-individual-suite
   :notification-airline-seat-legroom-extra            ic/notification-airline-seat-legroom-extra
   :notification-airline-seat-legroom-normal           ic/notification-airline-seat-legroom-normal
   :notification-airline-seat-legroom-reduced          ic/notification-airline-seat-legroom-reduced
   :notification-airline-seat-recline-extra            ic/notification-airline-seat-recline-extra
   :notification-airline-seat-recline-normal           ic/notification-airline-seat-recline-normal
   :notification-bluetooth-audio                       ic/notification-bluetooth-audio
   :notification-confirmation-number                   ic/notification-confirmation-number
   :notification-disc-full                             ic/notification-disc-full
   :notification-do-not-disturb-alt                    ic/notification-do-not-disturb-alt
   :notification-do-not-disturb-off                    ic/notification-do-not-disturb-off
   :notification-do-not-disturb-on                     ic/notification-do-not-disturb-on
   :notification-do-not-disturb                        ic/notification-do-not-disturb
   :notification-drive-eta                             ic/notification-drive-eta
   :notification-enhanced-encryption                   ic/notification-enhanced-encryption
   :notification-event-available                       ic/notification-event-available
   :notification-event-busy                            ic/notification-event-busy
   :notification-event-note                            ic/notification-event-note
   :notification-folder-special                        ic/notification-folder-special
   :notification-live-tv                               ic/notification-live-tv
   :notification-mms                                   ic/notification-mms
   :notification-more                                  ic/notification-more
   :notification-network-check                         ic/notification-network-check
   :notification-network-locked                        ic/notification-network-locked
   :notification-no-encryption                         ic/notification-no-encryption
   :notification-ondemand-video                        ic/notification-ondemand-video
   :notification-personal-video                        ic/notification-personal-video
   :notification-phone-bluetooth-speaker               ic/notification-phone-bluetooth-speaker
   :notification-phone-forwarded                       ic/notification-phone-forwarded
   :notification-phone-in-talk                         ic/notification-phone-in-talk
   :notification-phone-locked                          ic/notification-phone-locked
   :notification-phone-missed                          ic/notification-phone-missed
   :notification-phone-paused                          ic/notification-phone-paused
   :notification-power                                 ic/notification-power
   :notification-priority-high                         ic/notification-priority-high
   :notification-rv-hookup                             ic/notification-rv-hookup
   :notification-sd-card                               ic/notification-sd-card
   :notification-sim-card-alert                        ic/notification-sim-card-alert
   :notification-sms-failed                            ic/notification-sms-failed
   :notification-sms                                   ic/notification-sms
   :notification-sync-disabled                         ic/notification-sync-disabled
   :notification-sync-problem                          ic/notification-sync-problem
   :notification-sync                                  ic/notification-sync
   :notification-system-update                         ic/notification-system-update
   :notification-tap-and-play                          ic/notification-tap-and-play
   :notification-time-to-leave                         ic/notification-time-to-leave
   :notification-vibration                             ic/notification-vibration
   :notification-voice-chat                            ic/notification-voice-chat
   :notification-vpn-lock                              ic/notification-vpn-lock
   :notification-wc                                    ic/notification-wc
   :notification-wifi                                  ic/notification-wifi
   :places-ac-unit                                     ic/places-ac-unit
   :places-airport-shuttle                             ic/places-airport-shuttle
   :places-all-inclusive                               ic/places-all-inclusive
   :places-beach-access                                ic/places-beach-access
   :places-business-center                             ic/places-business-center
   :places-casino                                      ic/places-casino
   :places-child-care                                  ic/places-child-care
   :places-child-friendly                              ic/places-child-friendly
   :places-fitness-center                              ic/places-fitness-center
   :places-free-breakfast                              ic/places-free-breakfast
   :places-golf-course                                 ic/places-golf-course
   :places-hot-tub                                     ic/places-hot-tub
   :places-kitchen                                     ic/places-kitchen
   :places-pool                                        ic/places-pool
   :places-room-service                                ic/places-room-service
   :places-rv-hookup                                   ic/places-rv-hookup
   :places-smoke-free                                  ic/places-smoke-free
   :places-smoking-rooms                               ic/places-smoking-rooms
   :places-spa                                         ic/places-spa
   :social-cake                                        ic/social-cake
   :social-domain                                      ic/social-domain
   :social-group-add                                   ic/social-group-add
   :social-group                                       ic/social-group
   :social-location-city                               ic/social-location-city
   :social-mood-bad                                    ic/social-mood-bad
   :social-mood                                        ic/social-mood
   :social-notifications-active                        ic/social-notifications-active
   :social-notifications-none                          ic/social-notifications-none
   :social-notifications-off                           ic/social-notifications-off
   :social-notifications-paused                        ic/social-notifications-paused
   :social-notifications                               ic/social-notifications
   :social-pages                                       ic/social-pages
   :social-party-mode                                  ic/social-party-mode
   :social-people-outline                              ic/social-people-outline
   :social-people                                      ic/social-people
   :social-person-add                                  ic/social-person-add
   :social-person-outline                              ic/social-person-outline
   :social-person                                      ic/social-person
   :social-plus-one                                    ic/social-plus-one
   :social-poll                                        ic/social-poll
   :social-public                                      ic/social-public
   :social-school                                      ic/social-school
   :social-sentiment-dissatisfied                      ic/social-sentiment-dissatisfied
   :social-sentiment-neutral                           ic/social-sentiment-neutral
   :social-sentiment-satisfied                         ic/social-sentiment-satisfied
   :social-sentiment-very-dissatisfied                 ic/social-sentiment-very-dissatisfied
   :social-sentiment-very-satisfied                    ic/social-sentiment-very-satisfied
   :social-share                                       ic/social-share
   :social-whatshot                                    ic/social-whatshot
   :toggle-check-box-outline-blank                     ic/toggle-check-box-outline-blank
   :toggle-check-box                                   ic/toggle-check-box
   :toggle-indeterminate-check-box                     ic/toggle-indeterminate-check-box
   :toggle-radio-button-checked                        ic/toggle-radio-button-checked
   :toggle-radio-button-unchecked                      ic/toggle-radio-button-unchecked
   :toggle-star-border                                 ic/toggle-star-border
   :toggle-star-half                                   ic/toggle-star-half
   :toggle-star                                        ic/toggle-star})
